# Generated by Django 5.2.1 on 2025-05-19 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcliente',
            name='email',
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='rg',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilmedico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
