# Generated by Django 5.2.1 on 2025-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfilcliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
