# Generated by Django 5.2.1 on 2025-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilcliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
