# Generated by Django 5.2.1 on 2025-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilcliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
